# This is a basic workflow to help you get started with Actions

name: Generate Documentation

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ feature/OND211-380-generate-documentation ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "generate-doc"
  generate-doc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2.1.3

      - name: Install protoc and protoc-gen-doc
        run: |
          go get -u google.golang.org/protobuf/cmd/protoc-gen-go github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc
          export GOPATH=$(go env GOPATH)
          export PATH=$GOPATH/bin:$PATH

      # Runs a set of commands using the runners shell
      - name: Generate documentation from ONDEWO proto files
        run: |
          for f in $(find ondewo -name '*.proto')
          do
          	protoc -I. -Igoogleapis --doc_opt=markdown,$(basename ${f%.proto}.md) --doc_out=doc/$(dirname $f) $f
          done
